### ISSUE TITLE
Layout file has missing comma

### ISSUE THREAD

**Issue by orv1s** [dzeiocom/lucide-astro#19]
https://github.com/dzeiocom/lucide-astro/blob/7043c61277f09ebbcc77b2d940b4e3e205e733c4/src/.Layout.astro#L11

**Comment by Aviortheking** [comment]
shit sorry :( this will be fixed right now !

**Comment by Aviortheking** [comment]
Sorry again for everyone who has had this issue, I added more checks so that it does not reproduce #20
